# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-02 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='app key')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name_plural': 'api applications',
                'verbose_name': 'api application',
            },
        ),
        migrations.CreateModel(
            name='APIApplicationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=200, verbose_name='permission identifier')),
                ('granted', models.BooleanField(default=False, verbose_name='granted')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='shuup_jwt_permission.APIApplication', verbose_name='api application')),
            ],
            options={
                'verbose_name_plural': 'api application permissions',
                'verbose_name': 'api application permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apiapplicationpermission',
            unique_together=set([('application', 'permission')]),
        ),
    ]
